import { Idropdown, PWDInitINTERFACE } from "../Interface/InitInterface";

const sdpTypes: Idropdown[] = [
    { value:'', label: 'Select SDP Type For All' },
    { value: '55587, FWC,7122', label: 'Population Welfare Department - FWC' },
    { value: '50484, MSU,7121', label: 'Population Welfare Department - MSU' },
    { value: '50435, RHS,7120', label: 'Population Welfare Department - RHS-A' },
  ];

export const PWDinitModel: PWDInitINTERFACE = {
isLoading: false,
startDate:'',
endDate:'',
SDPdropdown: sdpTypes,
SDPdropdownValue: '',
districtDropdown:[],
districtValue:'',
centerDropdown:[],
centerValue:'',
AllReport:[],
FWCReport:[],
MSUReport:[],
RHSAReport:[],
linearData: [],
FWCOpenClose:[],
MSUOpenClose:[],
RHSAOpenClose:[],
AllOpenClose:[],
Allcount:'',
MSUcount:'',
RHSACount:'',
FWCCount:'',
openclose:[],
FWCOpenCloseRecord:[],
MSUOpenCloseRecord:[],
RHSAOpenCloseRecord:[],
ContraceptivesAlert:[],
contraceptiveStock:[],
attendanceRecord:[],
MonitoringReportRecord:[],
furnitureData:[],
officeGridRecord:[],
}
